{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMNwIvNZxOR5ZpE6GxzsYE0",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/regitaaajuairianiii-bit/tugas5fiskom/blob/main/app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# =========================================\n",
        "# EDU ANALYTICS DASHBOARD - STREAMLIT\n",
        "# =========================================\n",
        "\n",
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import plotly.express as px\n",
        "import plotly.graph_objects as go\n",
        "from sklearn.cluster import KMeans\n",
        "from sklearn.preprocessing import StandardScaler\n",
        "\n",
        "# ===============================\n",
        "# PAGE CONFIG\n",
        "# ===============================\n",
        "st.set_page_config(\n",
        "    page_title=\"Edu Analytics Dashboard\",\n",
        "    layout=\"wide\"\n",
        ")\n",
        "\n",
        "# ===============================\n",
        "# CUSTOM STYLE (Elegant Theme)\n",
        "# ===============================\n",
        "st.markdown(\"\"\"\n",
        "    <style>\n",
        "    .main {\n",
        "        background-color: #F8FAFC;\n",
        "    }\n",
        "    h1, h2, h3 {\n",
        "        color: #1E3A8A;\n",
        "        font-weight: 600;\n",
        "    }\n",
        "    .stMetric {\n",
        "        background-color: #FFFFFF;\n",
        "        padding: 15px;\n",
        "        border-radius: 12px;\n",
        "        box-shadow: 0px 4px 12px rgba(0,0,0,0.05);\n",
        "    }\n",
        "    </style>\n",
        "\"\"\", unsafe_allow_html=True)\n",
        "\n",
        "st.title(\"📊 Edu Analytics - Dashboard Analisis Soal\")\n",
        "st.markdown(\"Analisis kualitas butir soal berbasis data simulasi\")\n",
        "\n",
        "# ===============================\n",
        "# FILE UPLOAD\n",
        "# ===============================\n",
        "uploaded_file = st.file_uploader(\"Upload File Excel\", type=[\"xlsx\"])\n",
        "\n",
        "if uploaded_file is not None:\n",
        "\n",
        "    df = pd.read_excel(uploaded_file)\n",
        "    data = df.select_dtypes(include=np.number)\n",
        "\n",
        "    if data.shape[1] == 0:\n",
        "        st.error(\"File tidak memiliki kolom numerik.\")\n",
        "        st.stop()\n",
        "\n",
        "    # ===============================\n",
        "    # STATISTIK UMUM\n",
        "    # ===============================\n",
        "    jumlah_siswa = len(df)\n",
        "    jumlah_soal = data.shape[1]\n",
        "    rata_kelas = round(data.mean().mean(), 2)\n",
        "\n",
        "    col1, col2, col3 = st.columns(3)\n",
        "    col1.metric(\"Jumlah Siswa\", jumlah_siswa)\n",
        "    col2.metric(\"Jumlah Soal\", jumlah_soal)\n",
        "    col3.metric(\"Rata-rata Kelas\", rata_kelas)\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    # ===============================\n",
        "    # DISTRIBUSI NILAI TOTAL\n",
        "    # ===============================\n",
        "    st.subheader(\"📈 Distribusi Nilai Total\")\n",
        "\n",
        "    df[\"Total_Nilai\"] = data.sum(axis=1)\n",
        "\n",
        "    fig1 = px.histogram(\n",
        "        df,\n",
        "        x=\"Total_Nilai\",\n",
        "        nbins=10,\n",
        "        color_discrete_sequence=[\"#1E3A8A\"]\n",
        "    )\n",
        "\n",
        "    fig1.update_layout(template=\"plotly_white\")\n",
        "    st.plotly_chart(fig1, use_container_width=True)\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    # ===============================\n",
        "    # ANALISIS INDEKS KESUKARAN\n",
        "    # ===============================\n",
        "    st.subheader(\"📊 Analisis Indeks Kesukaran\")\n",
        "\n",
        "    mean_per_soal = data.mean()\n",
        "\n",
        "    def kategori_kesukaran(x):\n",
        "        if x >= 0.80:\n",
        "            return \"Sangat Mudah\"\n",
        "        elif x >= 0.60:\n",
        "            return \"Mudah\"\n",
        "        elif x >= 0.40:\n",
        "            return \"Sedang\"\n",
        "        elif x >= 0.20:\n",
        "            return \"Sulit\"\n",
        "        else:\n",
        "            return \"Sangat Sulit\"\n",
        "\n",
        "    indeks_df = pd.DataFrame({\n",
        "        \"Soal\": mean_per_soal.index,\n",
        "        \"Indeks Kesukaran\": mean_per_soal.values,\n",
        "        \"Kategori\": mean_per_soal.apply(kategori_kesukaran).values\n",
        "    }).sort_values(\"Indeks Kesukaran\")\n",
        "\n",
        "    fig2 = px.bar(\n",
        "        indeks_df,\n",
        "        x=\"Soal\",\n",
        "        y=\"Indeks Kesukaran\",\n",
        "        color=\"Kategori\",\n",
        "        color_discrete_map={\n",
        "            \"Sangat Mudah\": \"#16A34A\",\n",
        "            \"Mudah\": \"#22C55E\",\n",
        "            \"Sedang\": \"#EAB308\",\n",
        "            \"Sulit\": \"#F97316\",\n",
        "            \"Sangat Sulit\": \"#DC2626\"\n",
        "        }\n",
        "    )\n",
        "\n",
        "    fig2.update_layout(template=\"plotly_white\")\n",
        "    st.plotly_chart(fig2, use_container_width=True)\n",
        "\n",
        "    st.dataframe(indeks_df, use_container_width=True)\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    # ===============================\n",
        "    # RADAR CHART KOMPETENSI\n",
        "    # ===============================\n",
        "    st.subheader(\"🕸 Radar Chart Kompetensi\")\n",
        "\n",
        "    fig3 = go.Figure()\n",
        "\n",
        "    fig3.add_trace(go.Scatterpolar(\n",
        "        r=mean_per_soal.values,\n",
        "        theta=mean_per_soal.index,\n",
        "        fill='toself',\n",
        "        line=dict(color=\"#1E3A8A\")\n",
        "    ))\n",
        "\n",
        "    fig3.update_layout(\n",
        "        polar=dict(radialaxis=dict(visible=True, range=[0,1])),\n",
        "        showlegend=False,\n",
        "        template=\"plotly_white\"\n",
        "    )\n",
        "\n",
        "    st.plotly_chart(fig3, use_container_width=True)\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    # ===============================\n",
        "    # CLUSTERING SISWA\n",
        "    # ===============================\n",
        "    st.subheader(\"👥 Segmentasi Siswa\")\n",
        "\n",
        "    scaler = StandardScaler()\n",
        "    X_scaled = scaler.fit_transform(data)\n",
        "\n",
        "    kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)\n",
        "    df[\"Cluster\"] = kmeans.fit_predict(X_scaled)\n",
        "\n",
        "    fig4 = px.scatter(\n",
        "        df,\n",
        "        x=data.columns[0],\n",
        "        y=data.columns[1],\n",
        "        color=\"Cluster\",\n",
        "        color_continuous_scale=\"viridis\"\n",
        "    )\n",
        "\n",
        "    fig4.update_layout(template=\"plotly_white\")\n",
        "    st.plotly_chart(fig4, use_container_width=True)\n",
        "\n",
        "else:\n",
        "    st.info(\"Silakan upload file Excel untuk memulai analisis.\")"
      ],
      "metadata": {
        "id": "BErLq607B62V"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}